server:
  port: { server.port }
spring:
  config:
    import: optional:configserver:http://localhost:8888
feign:
  client:
    config:
      default:
        contract: feign.Contract.Default


document.path:  C:\\DZ\\IT\\Projects\\ProjectManager\\
document.format: xlsx

workbook.name: ReportExcel-
sheet.name: ProductReport



